version: '2.2'

services:
  app:
    image: azihassan/ticketing:v0.0.2
    depends_on:
      oracle-db:
        condition: service_healthy
    environment:
      - SPRING_DATASOURCE_URL=jdbc:oracle:thin:@oracle-db:1521/FREE
      - SPRING_DATASOURCE_USERNAME=system
      - SPRING_DATASOURCE_PASSWORD=oracle
      - SPRING_JPA_DATABASE_PLATFORM=org.hibernate.dialect.OracleDialect
    ports:
      - "8080:8080"

  oracle-db:
    image: gvenzl/oracle-free
    environment:
      - ORACLE_PASSWORD=oracle
    ports:
      - "1521:1521"
    healthcheck:
      test: ["CMD", "healthcheck.sh"]
      interval: 10s
      timeout: 5s
      retries: 10
